// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/auth/auth.proto

package examples_blog_service_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Auth service

type AuthService interface {
	CreateAuth(ctx context.Context, in *CreateAuthRequest, opts ...client.CallOption) (*CreateAuthResponse, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Auth_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Auth_PingPongService, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) CreateAuth(ctx context.Context, in *CreateAuthRequest, opts ...client.CallOption) (*CreateAuthResponse, error) {
	req := c.c.NewRequest(c.name, "Auth.CreateAuth", in)
	out := new(CreateAuthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Auth_StreamService, error) {
	req := c.c.NewRequest(c.name, "Auth.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &authServiceStream{stream}, nil
}

type Auth_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type authServiceStream struct {
	stream client.Stream
}

func (x *authServiceStream) Close() error {
	return x.stream.Close()
}

func (x *authServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *authService) PingPong(ctx context.Context, opts ...client.CallOption) (Auth_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Auth.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &authServicePingPong{stream}, nil
}

type Auth_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type authServicePingPong struct {
	stream client.Stream
}

func (x *authServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *authServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *authServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *authServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Auth service

type AuthHandler interface {
	CreateAuth(context.Context, *CreateAuthRequest, *CreateAuthResponse) error
	Stream(context.Context, *StreamingRequest, Auth_StreamStream) error
	PingPong(context.Context, Auth_PingPongStream) error
}

func RegisterAuthHandler(s server.Server, hdlr AuthHandler, opts ...server.HandlerOption) error {
	type auth interface {
		CreateAuth(ctx context.Context, in *CreateAuthRequest, out *CreateAuthResponse) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Auth struct {
		auth
	}
	h := &authHandler{hdlr}
	return s.Handle(s.NewHandler(&Auth{h}, opts...))
}

type authHandler struct {
	AuthHandler
}

func (h *authHandler) CreateAuth(ctx context.Context, in *CreateAuthRequest, out *CreateAuthResponse) error {
	return h.AuthHandler.CreateAuth(ctx, in, out)
}

func (h *authHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.AuthHandler.Stream(ctx, m, &authStreamStream{stream})
}

type Auth_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type authStreamStream struct {
	stream server.Stream
}

func (x *authStreamStream) Close() error {
	return x.stream.Close()
}

func (x *authStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *authHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.AuthHandler.PingPong(ctx, &authPingPongStream{stream})
}

type Auth_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type authPingPongStream struct {
	stream server.Stream
}

func (x *authPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *authPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *authPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
